name: Générer photos360.js

on:
  workflow_dispatch: # Permet de toujours le lancer manuellement
  push:
    paths:
      - '**/*.jpg'
      - '**/*.jpeg' # Optionnel, au cas où des extensions diffèrent

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le dépôt
        uses: actions/checkout@v4

      - name: Installer Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Générer photos360.js
        run: python3 make-photo360.js.py

      - name: Vérifier le fichier généré
        run: |
          echo "Contenu du dossier :"
          ls -la
          echo ""
          echo "Vérification de photos360.js :"
          ls -l photos360.js

      - name: Commit du fichier généré
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
          git add photos360.js
          
          # Le "|| echo" évite que l'action ne plante s'il n'y a pas de nouvelle photo
          git commit -m "Mise à jour automatique de photos360.js" || echo "Aucun changement"
          
          git push
